
name: Staging-frontend

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory-frontend: ./frontend
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm install
    - name: Build 
      run: npm run build
    - name: Unit Test
      run: npm run test:unit
    - name: E2E Test
      run: npm run test:e2e
